services:
  mongodb:
    image: mongo:7.0
    container_name: chat_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: study-chat
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - chat_network

  chat_backend:
    build: .
    container_name: chat_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: mongodb://admin:password123@mongodb:27017/study-chat?authSource=admin
      DATABASE_NAME: study-chat
      JWT_SECRET_KEY: your-production-secret-key-change-this-in-production
      JWT_ALGORITHM: HS256
      JWT_EXPIRE_MINUTES: 1440
      CORS_ORIGINS: http://localhost:3000,http://localhost:8080,http://localhost:5173,https://studysend.com,https://www.studysend.com
    networks:
      - chat_network
    volumes:
      - .:/app
    command: ["python", "run.py", "--production", "--workers", "2"]
    depends_on:
      - mongodb

networks:
  chat_network:
    driver: bridge

volumes:
  mongodb_data: